# Generated by Django 2.2.12 on 2020-05-13 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200513_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_attend_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 6, 17, 8, 637589)),
        ),
    ]
