# Generated by Django 2.2.12 on 2020-05-16 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200515_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recent_attend_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
