# Generated by Django 2.2.12 on 2020-05-13 06:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200513_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_attend_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 6, 17, 45, 648965, tzinfo=utc)),
        ),
    ]
