# Generated by Django 2.2.12 on 2020-05-13 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200513_0619'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', members.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용중'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='스태프 권한'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='수퍼유저 권한'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recent_attend_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 8, 1, 57, 605294, tzinfo=utc)),
        ),
    ]
