# Generated by Django 2.2.12 on 2020-05-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200513_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recent_attend_date',
        ),
    ]
