# Generated by Django 2.2.12 on 2020-05-13 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_user_recent_attend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_attend_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
