# Generated by Django 2.2.12 on 2020-05-13 08:33

from django.db import migrations
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20200513_0831'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', members.models.UserManager()),
            ],
        ),
    ]
