# Generated by Django 2.2.12 on 2020-05-23 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Saturday Worship', 'Sunday 4 Part'), ('Sunday Part 1 Worship', 'Sunday 1 Part'), ('Sunday Part 2 Worship', 'Sunday 2 Part'), ('Sunday Part 3 Worship', 'Sunday 3 Part'), ('Sunday Part 4 Worship', 'Sunday 4 Part'), ('Sunday Meeting', 'Sunday Meeting')], default='Saturday Worship', max_length=30)),
                ('pre_search', models.CharField(choices=[('참석', 'attendance'), ('불참', 'nonattendance'), ('미정', 'undefined')], default='undefined', max_length=30)),
                ('attend', models.BooleanField(default=False, verbose_name='출석 참여 여부')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_record', to='records.Record')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ManyToManyField(related_name='record_users', through='records.RecordResult', to=settings.AUTH_USER_MODEL),
        ),
    ]
