# Generated by Django 2.2.12 on 2020-05-16 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='2020-05-17 출석부', max_length=50, null=True)),
                ('service_type', models.CharField(choices=[('Saturday Worship', 'Sunday 4 Part'), ('Sunday Part 1 Worship', 'Sunday 1 Part'), ('Sunday Part 2 Worship', 'Sunday 2 Part'), ('Sunday Part 3 Worship', 'Sunday 3 Part'), ('Sunday Part 4 Worship', 'Sunday 4 Part'), ('Sunday 4 Meeting', 'Sunday 4 Meeting')], default='Saturday Worship', max_length=30)),
                ('attend', models.BooleanField(default=False, verbose_name='출석 참여 여부')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
